# === Model / training hyperparameters ===
image_h: 256           
image_w: 256
batch_size: 2
epochs: 20
lr: 0.0001
val_split: 0.2

# Enable Tensor Core speedups on GPUs that support it (safe to keep true)
mixed_precision: true

early_stopping_patience: 20
reduce_lr_patience: 5
reduce_lr_factor: 0.1
min_lr: 0.0000001